services:
  grafana:
    user: root
    container_name: 'platformbuilds-miradorstack-datasource'
    networks:
      - localdev_mirador-net
    ports:
      - "3000:3000"

    build:
      context: .
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-12.2.0}
        development: ${DEVELOPMENT:-false}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    volumes:
      - ../dist:/var/lib/grafana/plugins/platformbuilds-miradorstack-datasource
      - ../provisioning:/etc/grafana/provisioning
      - ..:/root/platformbuilds-miradorstack-datasource

    environment:
      NODE_ENV: production
      GF_LOG_FILTERS: plugin.platformbuilds-miradorstack-datasource:debug
      GF_LOG_LEVEL: info
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: platformbuilds-miradorstack-datasource
      GF_SECURITY_ADMIN_PASSWORD: admin

networks:
  localdev_mirador-net:
    external: true
